language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install: mvn install -B -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true

script: mvn test -B -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true

cache: false
